const express=require('express');const session=require('express-session');const SQLiteStore=require('connect-sqlite3')(session);const sqlite3=require('sqlite3').verbose();const multer=require('multer');const XLSX=require('xlsx');const bcrypt=require('bcryptjs');const path=require('path');const fs=require('fs');const crypto=require('crypto');
const app=express(),PORT=process.env.PORT||3000,DB_PATH=process.env.DB_PATH||path.join(__dirname,'klc.db'),UPLOAD_DIR=path.join(__dirname,'uploads');fs.mkdirSync(UPLOAD_DIR,{recursive:true});const db=new sqlite3.Database(DB_PATH),upload=multer({dest:UPLOAD_DIR});
app.use(express.json({limit:'50mb'}));app.use(express.urlencoded({extended:true}));app.use(session({store:new SQLiteStore({db:'sessions.db',dir:__dirname}),secret:process.env.SESSION_SECRET||'klc-dev-secret-change-me',resave:false,saveUninitialized:false,cookie:{maxAge:1000*60*60*12}}));app.use(express.static(path.join(__dirname,'public')));
const run=(s,p=[])=>new Promise((res,rej)=>db.run(s,p,function(e){e?rej(e):res(this)}));const get=(s,p=[])=>new Promise((res,rej)=>db.get(s,p,(e,r)=>e?rej(e):res(r)));const all=(s,p=[])=>new Promise((res,rej)=>db.all(s,p,(e,r)=>e?rej(e):res(r)));const id=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),clean=v=>String(v??'').trim();
function rol(r){r=clean(r).toLowerCase();return(r==='admin'||r==='מנהל')?'admin':'worker'}function login(req,res,next){if(!req.session.user)return res.status(401).json({error:'נדרשת כניסה'});next()}function admin(req,res,next){if(!req.session.user||rol(req.session.user.role)!=='admin')return res.status(403).json({error:'מנהל בלבד'});next()}function act(v){return v===1||v===true||v==='1'||v==='true'||v==='כן'}function lbl(t){return{pants:'השלמת מכנסיים',daily:'ליקוט יומי',melange:'מלאנז׳'}[t]||t}function code(t){return{pants:'P',daily:'D',melange:'M'}[t]||'X'}function storeNo(s){let m=String(s||'').match(/\d+/);return m?m[0].padStart(2,'0'):'00'}function qty(v){let n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)&&n>0?n:1}function norm(v){return clean(v).replace(/^\uFEFF/,'').replace(/[\u200E\u200F]/g,'').replace(/["׳״']/g,'').replace(/\s+/g,' ')}function rowVal(row,names){let w=names.map(norm);for(let k of Object.keys(row||{}))if(w.includes(norm(k))&&clean(row[k])!=='')return clean(row[k]);return''}
async function ensureCol(t,c,ty){let cols=await all(`PRAGMA table_info(${t})`);if(!cols.some(x=>x.name===c))await run(`ALTER TABLE ${t} ADD COLUMN ${c} ${ty}`)}async function nextWaveNo(store,t){let key=`${storeNo(store)}-${code(t)}`,cur=await get('SELECT counter FROM counters WHERE counter_key=?',[key]),n=(cur?.counter||0)+1;await run('INSERT OR REPLACE INTO counters(counter_key,counter) VALUES(?,?)',[key,n]);return`${storeNo(store)}-${code(t)}-${String(n).padStart(5,'0')}`}
function locParts(v){let s=String(v||'').trim().toUpperCase(),m=s.match(/^([A-Z]+)\s*[-_ ]?\s*(\d+)/);return m?{l:m[1],n:+m[2],r:s}:{l:'ZZZ',n:999999,r:s}}function locCmp(a,b){let x=locParts(a.location),y=locParts(b.location);return x.l.localeCompare(y.l)||x.n-y.n||x.r.localeCompare(y.r)}
async function init(){await run(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,code_plain TEXT NOT NULL,role TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL)`);await run(`CREATE TABLE IF NOT EXISTS waves(id TEXT PRIMARY KEY,wave_no TEXT NOT NULL,store TEXT NOT NULL,store_no TEXT NOT NULL,source_type TEXT NOT NULL,source_label TEXT NOT NULL,status TEXT NOT NULL,assigned_to TEXT,created_at TEXT NOT NULL,closed_at TEXT,close_reason TEXT,parent_wave_no TEXT)`);await run(`CREATE TABLE IF NOT EXISTS wave_items(id TEXT PRIMARY KEY,wave_id TEXT NOT NULL,model TEXT NOT NULL,mix TEXT NOT NULL DEFAULT 'A',qty REAL NOT NULL DEFAULT 1,location TEXT,source_file TEXT,status TEXT NOT NULL DEFAULT 'open',actual_mix TEXT,picked_model TEXT,picked_by TEXT,picked_at TEXT,created_at TEXT NOT NULL,import_id TEXT)`);await run(`CREATE TABLE IF NOT EXISTS locations(kind TEXT NOT NULL,model_key TEXT NOT NULL,location TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(kind,model_key))`);await run(`CREATE TABLE IF NOT EXISTS counters(counter_key TEXT PRIMARY KEY,counter INTEGER NOT NULL)`);await run(`CREATE TABLE IF NOT EXISTS imports(id TEXT PRIMARY KEY,filename TEXT NOT NULL,source_type TEXT NOT NULL,rows_count INTEGER NOT NULL,created_at TEXT NOT NULL)`);await ensureCol('wave_items','picked_model','TEXT');await ensureCol('wave_items','import_id','TEXT');await run("UPDATE users SET role='admin' WHERE role='מנהל'");await run("UPDATE users SET role='worker' WHERE role='עובד'");if(!await get("SELECT id FROM users WHERE username='admin'"))await run('INSERT INTO users(username,password_hash,code_plain,role,active,created_at) VALUES(?,?,?,?,1,?)',['admin',bcrypt.hashSync('1234',10),'1234','admin',now()])}
function wb(f){return XLSX.readFile(f,{cellDates:false,raw:false})}function sheetRows(w,s){let ws=w.Sheets[s];return ws?XLSX.utils.sheet_to_json(ws,{defval:'',raw:false}):[]}function aoa(w,s){let ws=w.Sheets[s];return ws?XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false}):[]}function byHeader(w,names){let want=names.map(norm);for(let s of w.SheetNames){let a=aoa(w,s);for(let i=0;i<Math.min(40,a.length);i++){let h=(a[i]||[]).map(norm);if(want.every(x=>h.includes(x))){let rows=[];for(let r=i+1;r<a.length;r++){let o={};(a[r]||[]).forEach((v,c)=>o[h[c]||`COL_${c}`]=v);rows.push(o)}return rows}}}return[]}
function normPants(w){return sheetRows(w,'ליקוט').map(r=>({store:rowVal(r,['קוד ושם מחסן','חנות','מחסן / חנות','מחסן']),model:[rowVal(r,['סוג מכנסיים','סוג']),rowVal(r,['צבע'])].filter(Boolean).join(' ').trim(),mix:rowVal(r,['מידה','מיקס','מיקס / מידה'])||'A',qty:qty(rowVal(r,['כמות לליקוט','כמות','ליקוט']))})).filter(x=>x.store&&x.model)}function normDaily(w){let arr=aoa(w,'ליקוט יומי'),out=[];for(let i=0;i<arr.length;i++){let r=arr[i]||[],model=clean(r[0]),mix=clean(r[1])||'A',store=clean(r[2]),q=qty(r[3]),str=[model,mix,store,clean(r[3])].join('|');if(i===0&&/(דגם|קוד פריט|מיקס|חנות|מחסן|כמות)/.test(str))continue;if(model&&store)out.push({model,mix,store,qty:q})}return out}function normMel(w){let rows=byHeader(w,['קוד ושם מחסן','קוד פריט','ליקוט']);if(!rows.length)rows=sheetRows(w,w.SheetNames[0]);return rows.map(r=>({store:rowVal(r,['קוד ושם מחסן']),model:rowVal(r,['קוד פריט']),mix:[rowVal(r,['צבע']),rowVal(r,['מידה'])].filter(Boolean).join('-')||'A',qty:qty(rowVal(r,['ליקוט','כמות']))})).filter(x=>x.store&&x.model)}function detect(w,name){let n=String(name||'').toLowerCase();if(n.includes('השלמות')||n.includes('מכנס'))return{sourceType:'pants',rows:normPants(w)};if(n.includes('דוח ליקוט')||n.includes('עדכון יומי')||w.SheetNames.includes('ליקוט יומי'))return{sourceType:'daily',rows:normDaily(w)};if(n.includes('מלאנז')||n.includes('מלנז'))return{sourceType:'melange',rows:normMel(w)};if(w.SheetNames.includes('ליקוט'))return{sourceType:'pants',rows:normPants(w)};return{sourceType:'melange',rows:normMel(w)}}
async function locationFor(model,t){model=clean(model);if(t==='daily'){let r=await get("SELECT location FROM locations WHERE kind='daily' AND model_key=?",[model]);return r?.location||''}if(t==='melange'){let p=model.length>=9?model.substring(3,9):model;let r=await get("SELECT location FROM locations WHERE kind='melange' AND model_key=?",[p]);if(r)return r.location;r=await get("SELECT location FROM locations WHERE kind='melange' AND model_key=?",[model]);return r?.location||''}return''}async function refreshLoc(kind){let items=await all('SELECT wi.id,wi.model,w.source_type FROM wave_items wi JOIN waves w ON w.id=wi.wave_id WHERE w.source_type=?',[kind]);for(let it of items)await run('UPDATE wave_items SET location=? WHERE id=?',[await locationFor(it.model,it.source_type),it.id])}async function findWave(store,t){return get("SELECT * FROM waves WHERE store=? AND source_type=? AND status IN ('open','assigned','active') ORDER BY created_at DESC LIMIT 1",[store,t])}async function withItems(w){let items=await all('SELECT * FROM wave_items WHERE wave_id=?',[w.id]);items.sort(locCmp);return{...w,items}}async function cleanup(){let e=await all('SELECT w.id FROM waves w LEFT JOIN wave_items wi ON wi.wave_id=w.id GROUP BY w.id HAVING COUNT(wi.id)=0');for(let w of e)await run('DELETE FROM waves WHERE id=?',[w.id])}
app.post('/api/login',async(req,res)=>{let u=await get('SELECT * FROM users WHERE username=? AND active=1',[clean(req.body.username)]);if(!u||!bcrypt.compareSync(clean(req.body.code),u.password_hash))return res.status(401).json({error:'שם משתמש או קוד שגויים'});req.session.user={username:u.username,role:rol(u.role)};res.json({user:req.session.user})});app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));app.get('/api/me',(req,res)=>res.json({user:req.session.user||null}));
app.get('/api/users',admin,async(req,res)=>res.json((await all('SELECT id,username,code_plain,role,active,created_at FROM users ORDER BY username')).map(u=>({...u,role:rol(u.role),role_label:rol(u.role)==='admin'?'מנהל':'עובד',active:act(u.active)}))));app.post('/api/users',admin,async(req,res)=>{try{await run('INSERT INTO users(username,password_hash,code_plain,role,active,created_at) VALUES(?,?,?,?,1,?)',[clean(req.body.username),bcrypt.hashSync(clean(req.body.code),10),clean(req.body.code),rol(req.body.role),now()]);res.json({ok:true})}catch(e){res.status(400).json({error:'שם משתמש כבר קיים'})}});app.patch('/api/users/:id',admin,async(req,res)=>{let u=await get('SELECT * FROM users WHERE id=?',[req.params.id]);if(!u)return res.status(404).json({error:'יוזר לא נמצא'});if(req.body.active!==undefined)await run('UPDATE users SET active=? WHERE id=?',[req.body.active?1:0,req.params.id]);if(req.body.role)await run('UPDATE users SET role=? WHERE id=?',[rol(req.body.role),req.params.id]);if(req.body.code)await run('UPDATE users SET password_hash=?,code_plain=? WHERE id=?',[bcrypt.hashSync(String(req.body.code),10),String(req.body.code),req.params.id]);if(req.body.username&&u.username!=='admin'){let nu=clean(req.body.username);await run('UPDATE users SET username=? WHERE id=?',[nu,req.params.id]);await run('UPDATE waves SET assigned_to=? WHERE assigned_to=?',[nu,u.username]);await run('UPDATE wave_items SET picked_by=? WHERE picked_by=?',[nu,u.username])}res.json({ok:true})});app.delete('/api/users/:id',admin,async(req,res)=>{let u=await get('SELECT * FROM users WHERE id=?',[req.params.id]);if(!u||u.username==='admin')return res.status(400).json({error:'לא ניתן למחוק'});await run("UPDATE waves SET assigned_to=NULL,status=CASE WHEN status IN ('assigned','active') THEN 'open' ELSE status END WHERE assigned_to=?",[u.username]);await run('DELETE FROM users WHERE id=?',[req.params.id]);res.json({ok:true})});
app.post('/api/upload/picking',admin,upload.array('files',30),async(req,res)=>{let total={added:0,created:0,merged:0,files:[]};for(let f of req.files||[]){let w=wb(f.path),d=detect(w,f.originalname),rows=d.rows;total.files.push({filename:f.originalname,label:lbl(d.sourceType),rows:rows.length});if(!rows.length)continue;let importId=id();await run('INSERT INTO imports(id,filename,source_type,rows_count,created_at) VALUES(?,?,?,?,?)',[importId,f.originalname,d.sourceType,rows.length,now()]);let by={};for(let r of rows)if(r.store&&r.model)(by[r.store]??=[]).push(r);for(let [store,items] of Object.entries(by)){let wave=await findWave(store,d.sourceType),wid;if(wave){wid=wave.id;total.merged++}else{wid=id();await run('INSERT INTO waves(id,wave_no,store,store_no,source_type,source_label,status,created_at) VALUES(?,?,?,?,?,?,?,?)',[wid,await nextWaveNo(store,d.sourceType),store,storeNo(store),d.sourceType,lbl(d.sourceType),'open',now()]);total.created++}for(let it of items){await run('INSERT INTO wave_items(id,wave_id,model,mix,qty,location,source_file,status,created_at,import_id) VALUES(?,?,?,?,?,?,?,?,?,?)',[id(),wid,it.model,it.mix||'A',it.qty||1,await locationFor(it.model,d.sourceType),f.originalname,'open',now(),importId]);total.added++}}}res.json(total)});
app.post('/api/upload/locations/:kind',admin,upload.single('file'),async(req,res)=>{let kind=req.params.kind;if(!req.file)return res.status(400).json({error:'לא נבחר קובץ'});let w=wb(req.file.path),count=0;if(kind==='daily'){let rows=byHeader(w,['קוד פריט','תאור']);if(!rows.length)rows=byHeader(w,['קוד פריט','תיאור']);if(!rows.length)rows=XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]],{defval:'',raw:false});for(let r of rows){let m=rowVal(r,['קוד פריט','דגם','פריט']),l=rowVal(r,['תאור','תיאור','מיקום','תא אחסון']);if(m&&l){await run('INSERT OR REPLACE INTO locations(kind,model_key,location,updated_at) VALUES(?,?,?,?)',['daily',clean(m),clean(l),now()]);count++}}await refreshLoc('daily')}else if(kind==='melange'){let rows=sheetRows(w,'מתעדכן קבוע');if(!rows.length)rows=byHeader(w,['דגם','מיקום']);for(let r of rows){let m=rowVal(r,['דגם']),l=rowVal(r,['מיקום','תאור','תיאור']);if(m&&l){await run('INSERT OR REPLACE INTO locations(kind,model_key,location,updated_at) VALUES(?,?,?,?)',['melange',clean(m),clean(l),now()]);count++}}await refreshLoc('melange')}res.json({count})});
app.get('/api/waves',login,async(req,res)=>{let rows=rol(req.session.user.role)==='admin'?await all('SELECT * FROM waves ORDER BY store_no ASC,wave_no ASC'):await all("SELECT * FROM waves WHERE assigned_to=? AND status IN ('open','assigned','active') ORDER BY created_at ASC",[req.session.user.username]);res.json(await Promise.all(rows.map(withItems)))});app.post('/api/assign',admin,async(req,res)=>{let w=await get('SELECT assigned_to FROM waves WHERE id=?',[req.body.waveId]);if(w?.assigned_to)return res.status(400).json({error:'הגל כבר משויך'});await run("UPDATE waves SET assigned_to=?,status=CASE WHEN status='open' THEN 'assigned' ELSE status END WHERE id=?",[clean(req.body.username),req.body.waveId]);res.json({ok:true})});app.post('/api/assign/bulk',admin,async(req,res)=>{let ids=Array.isArray(req.body.waveIds)?req.body.waveIds:[],u=clean(req.body.username),assigned=0,skipped=0;if(!ids.length||!u)return res.status(400).json({error:'חסר עובד או גלים'});for(let wid of ids){let w=await get('SELECT assigned_to FROM waves WHERE id=?',[wid]);if(!w||w.assigned_to){skipped++;continue}await run("UPDATE waves SET assigned_to=?,status=CASE WHEN status='open' THEN 'assigned' ELSE status END WHERE id=?",[u,wid]);assigned++}res.json({assigned,skipped})});app.post('/api/wave/unassign',admin,async(req,res)=>{await run("UPDATE waves SET assigned_to=NULL,status=CASE WHEN status IN ('assigned','active') THEN 'open' ELSE status END WHERE id=?",[req.body.waveId]);res.json({ok:true})});app.delete('/api/waves/:id',admin,async(req,res)=>{await run('DELETE FROM wave_items WHERE wave_id=?',[req.params.id]);await run('DELETE FROM waves WHERE id=?',[req.params.id]);res.json({ok:true})});app.post('/api/waves/bulk-delete',admin,async(req,res)=>{let ids=Array.isArray(req.body.waveIds)?req.body.waveIds:[];for(let wid of ids){await run('DELETE FROM wave_items WHERE wave_id=?',[wid]);await run('DELETE FROM waves WHERE id=?',[wid])}res.json({deleted:ids.length})});
app.post('/api/item/status',login,async(req,res)=>{let item=await get('SELECT wi.*,w.assigned_to,w.id AS wave_id,w.source_type,w.source_label FROM wave_items wi JOIN waves w ON w.id=wi.wave_id WHERE wi.id=?',[req.body.itemId]);if(!item)return res.status(404).json({error:'פריט לא נמצא'});if(rol(req.session.user.role)!=='admin'&&item.assigned_to!==req.session.user.username)return res.status(403).json({error:'אין הרשאה לפריט הזה'});let status=clean(req.body.status),pm=clean(req.body.pickedModel||''),isP=item.source_type==='pants'||String(item.source_label||'').includes('מכנס');if(isP&&status==='picked'&&!pm)return res.status(400).json({error:'חובה לסרוק או להזין ברקוד לפני סימון לוקט'});if(status==='open')await run("UPDATE wave_items SET status='open',actual_mix='',picked_model='',picked_by='',picked_at='' WHERE id=?",[req.body.itemId]);else{await run('UPDATE wave_items SET status=?,actual_mix=?,picked_model=?,picked_by=?,picked_at=? WHERE id=?',[status,req.body.actualMix||'',pm,req.session.user.username,now(),req.body.itemId]);await run("UPDATE waves SET status='active' WHERE id=? AND status IN ('open','assigned')",[item.wave_id])}res.json({ok:true})});app.post('/api/wave/complete',login,async(req,res)=>{let o=await get("SELECT COUNT(*) c FROM wave_items WHERE wave_id=? AND status='open'",[req.body.waveId]);if((o?.c||0)>0)return res.status(400).json({error:`יש עוד ${o.c} קרטונים פתוחים בגל הזה. אפשר לסגור משטח מלא או להשלים סטטוס לכל השורות.`});await run("UPDATE waves SET status='completed',closed_at=?,close_reason='ליקוט הושלם' WHERE id=?",[now(),req.body.waveId]);res.json({message:'ליקוט הושלם - סגור משטח'})});app.post('/api/wave/pallet-full',login,async(req,res)=>{let w=await get('SELECT * FROM waves WHERE id=?',[req.body.waveId]);let open=await all("SELECT * FROM wave_items WHERE wave_id=? AND status='open'",[req.body.waveId]);if(!open.length)return res.status(400).json({error:'אין פריטים פתוחים לגל המשך'});let nid=id(),no=await nextWaveNo(w.store,w.source_type);await run('INSERT INTO waves(id,wave_no,store,store_no,source_type,source_label,status,assigned_to,created_at,parent_wave_no) VALUES(?,?,?,?,?,?,?,?,?,?)',[nid,no,w.store,w.store_no,w.source_type,w.source_label,w.assigned_to?'assigned':'open',w.assigned_to,now(),w.wave_no]);for(let it of open){await run('INSERT INTO wave_items(id,wave_id,model,mix,qty,location,source_file,status,created_at,import_id) VALUES(?,?,?,?,?,?,?,?,?,?)',[id(),nid,it.model,it.mix,it.qty,it.location,it.source_file,'open',now(),it.import_id]);await run('DELETE FROM wave_items WHERE id=?',[it.id])}await run("UPDATE waves SET status='pallet_full',closed_at=?,close_reason='משטח מלא' WHERE id=?",[now(),req.body.waveId]);res.json({newWaveNo:no})});
async function analytics(){return all(`SELECT w.id wave_id,w.wave_no,w.store,w.source_type,w.source_label,w.assigned_to,w.status wave_status,w.closed_at,w.close_reason,wi.id item_id,wi.model,wi.mix,wi.qty,wi.location,wi.status,wi.actual_mix,wi.picked_model,wi.picked_by,wi.picked_at,wi.source_file FROM wave_items wi JOIN waves w ON w.id=wi.wave_id ORDER BY COALESCE(wi.picked_at,wi.created_at) DESC`)}app.get('/api/analytics',admin,async(req,res)=>res.json(await analytics()));app.get('/api/my-performance',login,async(req,res)=>res.json((await analytics()).filter(r=>r.assigned_to===req.session.user.username||r.picked_by===req.session.user.username)));app.get('/api/imports',admin,async(req,res)=>{let im=await all('SELECT * FROM imports ORDER BY created_at DESC'),out=[];for(let x of im){let s=await get("SELECT COUNT(*) total,SUM(CASE WHEN status!='open' THEN 1 ELSE 0 END) done FROM wave_items WHERE import_id=?",[x.id]);let t=s?.total||0,d=s?.done||0;out.push({...x,source_label:lbl(x.source_type),total_items:t,done_items:d,percent:t?Math.round(d/t*100):0,completed:t>0&&d===t})}res.json(out)});app.delete('/api/imports/:id',admin,async(req,res)=>{await run('DELETE FROM wave_items WHERE import_id=?',[req.params.id]);await run('DELETE FROM imports WHERE id=?',[req.params.id]);await cleanup();res.json({ok:true})});app.get('/api/analytics/export',admin,async(req,res)=>{let rows=await analytics(),w=clean(req.query.worker||'all'),st=clean(req.query.status||'all'),tp=clean(req.query.sourceType||'all'),dates=clean(req.query.dates||'').split(',').map(x=>x.trim()).filter(Boolean);rows=rows.filter(r=>(w==='all'||r.picked_by===w||r.assigned_to===w)&&(st==='all'||r.status===st)&&(tp==='all'||r.source_type===tp)&&(!dates.length||dates.some(d=>String(r.picked_at||'').startsWith(d)))).map(r=>({'גל':r.wave_no,'סוג גל':r.source_label,'חנות':r.store,'עובד משויך':r.assigned_to,'דגם נדרש':r.model,'ברקוד שנסרק':r.picked_model,'מיקס':r.mix,'כמות':r.qty,'מיקום':r.location,'סטטוס':r.status,'מיקס בפועל':r.actual_mix,'בוצע ע״י':r.picked_by,'תאריך':r.picked_at,'קובץ מקור':r.source_file}));let ws=XLSX.utils.json_to_sheet(rows),book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,ws,'ניתוח נתונים');let buf=XLSX.write(book,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Disposition','attachment; filename="KLC_analytics.xlsx"');res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.send(buf)});
init().then(()=>app.listen(PORT,()=>console.log('KLC v2.0 running on port '+PORT)));


// KLC v2.1.1 - ברקוד בכל אורך, בלי מגבלת 6 ספרות
app.post("/api/item/status_barcode", login, async (req,res)=>{
  const itemId = req.body.itemId || req.body.item_id;
  const status = String(req.body.status || "").trim();
  const barcode = String(req.body.barcode || req.body.pickedModel || req.body.picked_model || "").trim();
  const actualMix = req.body.actualMix || req.body.actual_mix || "";

  const item = await get(`SELECT wi.*, w.assigned_to, w.id AS wave_id, w.source_type, w.source_label
    FROM wave_items wi
    JOIN waves w ON w.id = wi.wave_id
    WHERE wi.id=?`, [itemId]);

  if(!item) return res.status(404).json({error:"פריט לא נמצא"});

  if(rol(req.session.user.role)!=="admin" && item.assigned_to !== req.session.user.username){
    return res.status(403).json({error:"אין הרשאה לפריט הזה"});
  }

  const isPants = String(item.source_type || "").toLowerCase() === "pants" || String(item.source_label || "").includes("מכנס");

  if(isPants && status === "picked" && !barcode){
    return res.status(400).json({error:"חובה לסרוק או להזין ברקוד לפני סימון לוקט"});
  }

  if(status === "open"){
    await run(`UPDATE wave_items
      SET status='open', actual_mix='', picked_model='', picked_by='', picked_at=''
      WHERE id=?`, [itemId]);
  } else {
    await run(`UPDATE wave_items
      SET status=?, actual_mix=?, picked_model=?, picked_by=?, picked_at=?
      WHERE id=?`, [status, actualMix || "", barcode || "", req.session.user.username, now(), itemId]);

    await run("UPDATE waves SET status='active' WHERE id=? AND status IN ('open','assigned')", [item.wave_id]);
  }

  res.json({ok:true});
});

// KLC v2.2 - endpoint בטוח לברקוד בכל אורך
app.post("/api/item/status_barcode_v22", login, async (req,res)=>{
  const itemId=req.body.itemId||req.body.item_id;
  const status=String(req.body.status||"").trim();
  const barcode=String(req.body.barcode||req.body.pickedModel||"").trim();
  const actualMix=req.body.actualMix||"";
  const item=await get(`SELECT wi.*, w.assigned_to, w.id AS wave_id, w.source_type, w.source_label
    FROM wave_items wi JOIN waves w ON w.id=wi.wave_id WHERE wi.id=?`,[itemId]);
  if(!item) return res.status(404).json({error:"פריט לא נמצא"});
  if(rol(req.session.user.role)!=="admin" && item.assigned_to!==req.session.user.username){
    return res.status(403).json({error:"אין הרשאה לפריט הזה"});
  }
  const isPants=String(item.source_type||"").toLowerCase()==="pants" || String(item.source_label||"").includes("מכנס");
  if(isPants && status==="picked" && !barcode){
    return res.status(400).json({error:"חובה לסרוק או להזין ברקוד לפני סימון לוקט"});
  }
  if(status==="open"){
    await run(`UPDATE wave_items SET status='open', actual_mix='', picked_model='', picked_by='', picked_at='' WHERE id=?`,[itemId]);
  }else{
    await run(`UPDATE wave_items SET status=?, actual_mix=?, picked_model=?, picked_by=?, picked_at=? WHERE id=?`,
      [status,actualMix||"",barcode||"",req.session.user.username,now(),itemId]);
    await run("UPDATE waves SET status='active' WHERE id=? AND status IN ('open','assigned')",[item.wave_id]);
  }
  res.json({ok:true});
});
